api:
  build: .
  ports:
    - "8080:8080"
    - "5858:5858"
  volumes:
    - ".:/usr/src/app"
    - "/usr/src/app/node_modules"
  environment:
    - VIRTUAL_HOST=api.eksiapi.dev
    - VIRTUAL_PORT=8080
  links:
    - elasticsearch
server:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
elasticsearch:
  image: elasticsearch:latest
  environment:
    - network.host=0.0.0.0
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  mem_limit: 1g
  ports:
    - "9200:9200"
    - "9300:9300"
